services:
  app:
    ports:
      - "8282:80"
    volumes:
      - ./app/vendor:/var/www/html/vendor

  partner-mock:
    ports:
      - "8283:8082"

  redis:
    ports:
      - "6379:6379"

networks:
  proxy-network:
    external: false